_Recoverable Error_
```rust
enum Result<T, E> {
    Ok(T),
    Err(E),
}
```
- The `T` and `E` are generic type parameters [ Chapter 10 ]
- Difference between `Option<T>` and `Result<T,E>` ?
	- `Option` can just represent _that_ an operation has failed, but `Result` can explain (all the reasons) _why_  the operation has failed.
	- `Option<T>` returns `Some,None`. 
	- `Result<T,E>` returns `Ok,Err`
		- eg: `parse(), File::open(), read_to_string()`

---
- The return type of `File::open` is a `Result<T, E>` which makes it easier to handle if file does not exist or no permissions to access it.
	- if `Ok` then `std::fs::File`
	- if `Err` then `std::io::Error` struct
		- `io::Error` has `kind` method to get `io::ErrorKind` value.
			- `io::ErrorKind` is an enum which represents different kinds of `io` operation error.
			- eg: `ErrorKind::NotFound` for FileNotFound
```rust
// panic the program if file not found
use std::fs::File;
let greeting_file = match File::open("hello.txt") {
	Ok(file) => file, 
	Err(error) => panic!("Problem opening the file: {:?}",error),
};

////////////////////////////////
// Shortcut to Panic an Error, rather than using match
/////////////////////////////

// by default Panics for error
let greeting_file = File::open("hello.txt").unwrap();
// to give more context to Panic message, use expect()
let greeting_file = File::open("hello.txt").expect("hello.txt should be included in this project");

```
- the `unwrap` and `expect` methods are very handy when prototyping, before you’re ready to decide how to handle errors. They leave clear markers in your code for when you’re ready to make your program more robust.
	- which means dont leave your code with `unwrap()` and `expect()`, do the proper error handling for `release` mode.
----

#### Handling different Errors
-  Handling FIleNotFound and other errors separately.
	- For FileNotFound, we are creating the file in the `inner match`
```rust
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let greeting_file_result = File::open("hello.txt");

    let greeting_file = match greeting_file_result {
        Ok(file) => file,
        Err(error) => match error.kind() {
            ErrorKind::NotFound => match File::create("hello.txt") {
                Ok(fc) => fc,
                Err(e) => panic!("Problem creating the file: {:?}", e),
            },
            other_error => {
                panic!("Problem opening the file: {:?}", other_error);
            }
        },
    };
}
```
#### Alternatives to Using match with Result<T, E>
Here's an alternative code using `closures` [ chapter 13 ]
- These methods can be more concise than using `match` when handling `Result<T, E>` values in your code.
- cleaner to read
```rust
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let greeting_file = File::open("hello.txt")
	    .unwrap_or_else(|error| {
        if error.kind() == ErrorKind::NotFound {
            File::create("hello.txt")
	            .unwrap_or_else(|error| {
                panic!("Problem creating the file: {:?}", error);
            })
        } else {
            panic!("Problem opening the file: {:?}", error);
        }
    });
}
```
---
#### Propagating Errors
_Returning the error instead of crashing (panic!-ing) the program._
- When a function’s implementation calls something that might fail, instead of handling the error within the function itself, it can return the error to the calling code so that it can decide what to do. This is known as _propagating_ error.
- The following function returns `Result<String, Error>`, hence if the task succeeds the fn will return `String` or else the `error`, instead of crashing the program.
- `File::open` and `read_to_string()` both returns `Result<T,E>`
- if `File::open` and `read_to_string()` both results in `Ok()` then only the `username` is returned, else `Err(e)`.
```rust
fn read_username_from_file() -> Result<String, io::Error> {
    let username_file_result = File::open("hello.txt");

    let mut username_file = match username_file_result {
        Ok(file) => file,
        Err(e) => return Err(e), // return fn after first error and dont go beyond this.
    };

    let mut username = String::new();

	// match is an expression, hence return keyword not needed.
    match username_file.read_to_string(&mut username) {
        Ok(_) => Ok(username),
        Err(e) => Err(e),
    }
}
```
##### Shortcut for Propagating errors
_This pattern of propagating errors is so common in Rust that Rust provides the question mark operator `?` to make this easier._
- Shorter version using `?` operator.
- for `Error` case, the `?` returns the code right away.
```rust
fn read_username_from_file() -> Result<String, io::Error> {
    let mut username_file = File::open("hello.txt")?;
    let mut username = String::new();
    username_file.read_to_string(&mut username)?;
    Ok(username)
}
```
- EVEN MORE SHORTER!
	- return an `Ok` value containing `username` when both `File::open` and `read_to_string` succeed
```rust
fn read_username_from_file() -> Result<String, io::Error> {
    let mut username = String::new();

    File::open("hello.txt")?.read_to_string(&mut username)?;

    Ok(username)
}
```
- OK, THE SHORTEST
	- Reading a file into a string is a fairly common operation, so the standard library provides the convenient `fs::read_to_string` function that opens the file, creates a new `String`, reads the contents of the file, puts the contents into that `String`, and returns it
```rust
fn read_username_from_file() -> Result<String, io::Error> {
    fs::read_to_string("hello.txt")
}
```
---
#### Where `?` can be used
- `?` operator can be used in a function that returns `Result`, `Option`, or another type that implements `FromResidual`. Example:
	- Function return `Result<String, io::Error>` 
	- `File::open("hello.txt")?` also returns `Result<String, io::Error>`
	- Hence `?` can be used with `File::open()` in this function.
- The `?` operator won’t automatically convert a `Result` to an `Option` or vice versa where the Function return type mismatches with `?`; 
- in those cases, do the conversion explicitly:
	- `Result::ok` - Result -> Option conversion
	- `Option::ok_or` - Option -> Result conversion
---
- An example of Incompatible fn return with `?`:
```rust
// Compile Error.
fn main() {
    let greeting_file = File::open("hello.txt")?;
}
```
- here `main()` returns `()` while `?` returns `Result<T,E>`.
- To fix the error, you have two choices. 
	- change the return type of your function to be compatible with the value you’re using the `?` operator on.
	- use a `match` or one of the `Result<T, E>` methods to handle the `Result<T, E>` in whatever way is appropriate.
- We have changed the return type of `main` to be `Result<(), Box<dyn Error>>` and added a return value `Ok(())` to the end.
```rust
fn main() -> Result<(), Box<dyn Error>> {
    let greeting_file = File::open("hello.txt")?;

    Ok(())
}
```
- The `Box<dyn Error>` type is a _trait object_, which we’ll talk about in the [“Using Trait Objects that Allow for Values of Different Types”](https://rust-book.cs.brown.edu/ch17-02-trait-objects.html#using-trait-objects-that-allow-for-values-of-different-types) section in Chapter 17. For now, you can read `Box<dyn Error>` to mean “any kind of error.” Using `?` on a `Result` value in a `main` function with the error type `Box<dyn Error>` is allowed, because it allows any `Err` value to be returned early. Even though the body of this `main` function will only ever return errors of type `std::io::Error`, by specifying `Box<dyn Error>`, this signature will continue to be correct even if more code that returns other errors is added to the body of `main`.

---
- An example of `?` with `Option<T>`
```rust
// finds the last character of the first line in the given text
fn last_char_of_first_line(text: &str) -> Option<char> {
    text.lines().next()?.chars().last()
}
```
